apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversortemperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversortemperatura
  template:
    metadata:
      labels:
        app: conversortemperatura
    spec:
      containers:
      - name:  conversortemperatura
        image: rsabatini/conversor-temperatura:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec: 
  selector:
    app: conversortemperatura
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort
